name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - '[0-9]+.[0-9]+-dev'
      - '[0-9]+.[0-9]+.[0-9]+-dev'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      - name: Update job summary
        if: steps.release.outputs.release_created
        run: |
          test -n '${{ steps.release.outputs.html_url }}'
          echo ':robot: Release is at ${{ steps.release.outputs.html_url }} :sunflower:' >> \
            $GITHUB_STEP_SUMMARY

  upload-assets:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/android-build
        with:
          check-build: false
          exclude-ci-info: true
          release-debug-opt: false
          upload-artifacts: false
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            ${{ env.ARTIFACTS_DIR }}/*.apk{,.md5,.sha256} --clobber
